name: uicons_brands
description: A Flutter package projectc for using UIcons Brands Icon Pack as IconData.
version: 1.0.0
repository: "https://github.com/redleafsofts/uicons_flutter"
homepage: "https://www.flaticon.com/uicons/interface-icons"

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: uicons_brands
      fonts:
       - asset: font/uicons_brands.ttf