name: uicons_brands
description: UIcons Brands Flutter package project.
version: 1.0.0
homepage: "https://www.flaticon.com/uicons/interface-icons"

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: uicons_brands
      fonts:
       - asset: font/uicons_brands.ttf