name: uicons
description: A Flutter package project for using UIcons Icon Pack as IconData.
version: 1.0.1
homepage: "https://github.com/redleafsofts/uicons_flutter/tree/main/uicons"
repository: "https://github.com/redleafsofts/uicons_flutter/tree/main/uicons"

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  uicons_bold_rounded: ^1.0.0
  uicons_bold_straight: ^1.0.0
  uicons_brands: ^1.0.0
  uicons_regular_rounded: ^1.0.0
  uicons_regular_straight: ^1.0.0
  uicons_solid_rounded: ^1.0.0
  uicons_solid_straight: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0