name: uicons_regular_rounded
description: Flutter Icons for UIcons Regular Rounded.
version: 1.0.0
repository: "https://github.com/redleafsofts/uicons_flutter/tree/main/uicons_regular_rounded"
homepage: "https://www.flaticon.com/uicons/interface-icons"

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: uicons_regular_rounded
      fonts:
       - asset: font/uicons_regular_rounded.ttf